---
- name: network-manager role
  tags:
  - network-manager
  block:

  # gather facts
  - name: Gather interface facts
    ansible.builtin.setup:
      filter:
      - ansible_interfaces

  # set fact
  - name: Set fact for primary wifi interface
    ansible.builtin.set_fact:
      __network_manager_primary_wifi: "{{ ansible_facts.interfaces | select('match', '^wl') | list | first }}"

  # debug
  - ansible.builtin.debug:
      var: __network_manager_primary_wifi

  # wifi connections
  - when: network_manager_wifi_connections | length > 0
    ansible.builtin.import_tasks: wifi.yml

  # dispatcher scripts
  - ansible.builtin.import_tasks: dispatcher.yml
