---
- name: network-manager role
  tags:
  - network-manager
  block:

  # gather facts
  - name: Gather interface facts
    ansible.builtin.setup:
      filter:
      - ansible_interfaces

  # debug
  - ansible.builtin.debug:
      var: ansible_facts

  # set fact
  - name: Set fact for primary wifi interface
    ansible.builtin.set_fact:
      __network_manager_primary_wifi: "{{ ansible_facts.interfaces | select('match', '^wl') | list | first }}"

  # wifi connections
  - when:
    - __network_manager_primary_wifi is defined
    - network_manager_wifi_connections | length > 0
    block:

    # assertions
    - name: Assertions for wifi connections
      loop: "{{ network_manager_wifi_connections }}"
      loop_control:
        loop_var: connection
      ansible.builtin.assert:
        that:
        - connection.name != None
        - connection.ssid != None
        - connection.psk != None

    # setup wifi connections
    - name: Setup wifi connections
      become: true
      notify: Reload NetworkManager
      loop: "{{ network_manager_wifi_connections }}"
      loop_control:
        loop_var: connection
      community.general.nmcli:
        type: wifi
        state: present
        conn_name: "{{ connection.name }}"
        ifname: "{{ __network_manager_primary_wifi }}"
        autoconnect: "{{ connection.autoconnect | default(false) }}"
        ssid: "{{ connection.ssid }}"
        method4: "{{ connection.method4 | default('auto') }}"
        method6: "{{ connection.method6 | default('auto') }}"
        wifi:
          mode: "{{ connection.mode | default('infrastructure') }}"
        wifi_sec:
          key-mgmt: "{{ connection.key_mgmt | default('wpa-psk') }}"
          psk: "{{ connection.psk }}"

  # dispatcher scripts
  - block:

    # pre-down
    - when: network_manager_dispatcher_pre_down | length > 0
      name: Copy pre-down dispatcher scripts
      become: true
      loop: "{{ network_manager_dispatcher_pre_down }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/NetworkManager/dispatcher.d/pre-down.d
        owner: root
        mode: u=rwx,g=,o=rx

    # pre-up
    - when: network_manager_dispatcher_pre_up | length > 0
      name: Copy pre-up dispatcher scripts
      become: true
      loop: "{{ network_manager_dispatcher_pre_up }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/NetworkManager/dispatcher.d/pre-up.d
        owner: root
        mode: u=rwx,g=,o=rx

    # no-wait
    - when: network_manager_dispatcher_no_wait | length > 0
      name: Copy no-wait dispatcher scripts
      become: true
      loop: "{{ network_manager_dispatcher_no_wait }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/NetworkManager/dispatcher.d/no-wait.d
        owner: root
        mode: u=rwx,g=,o=rx