---
# assertions
- name: Assertions for wifi connections
  loop: "{{ network_manager_connections_wifi }}"
  loop_control:
    loop_var: connection
  ansible.builtin.assert:
    that:
    - connection.name != None
    - connection.ssid != None
    - connection.psk != None
    - connection.state in ['present','absent']
    - __network_manager_primary_wifi != None

# setup wifi connections
- name: Setup wifi connections
  become: true
  notify: Reload NetworkManager
  loop: "{{ network_manager_connections_wifi }}"
  loop_control:
    loop_var: connection
  no_log: true
  community.general.nmcli:
    type: wifi
    state: "{{ connection.state }}"
    conn_name: "{{ connection.name }}" # The name used to call the connection. Pattern is <type>[-<ifname>][-<num>].
    ifname: "{{ __network_manager_primary_wifi }}"
    autoconnect: "{{ connection.autoconnect }}"
    ssid: "{{ connection.ssid }}"
    method4: "{{ connection.method4 }}"
    method6: "{{ connection.method6 }}"
    wifi:
      mode: "{{ connection.mode }}"
    wifi_sec:
      key-mgmt: "{{ connection.key_mgmt }}"
      psk: "{{ connection.psk }}"